# Generated by Django 5.2.17 on 2026-09-19 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('revision', models.PositiveIntegerField()),
                ('view', models.CharField(max_length=16)),
                ('camera', models.JSONField(null=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('image', models.BinaryField(null=True)),
                ('error', models.JSONField(null=True)),
                ('model_warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenelayout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scene', 'request_id'), name='unique_scene_capture_request')],
            },
        ),
    ]
