# Generated by Django 5.2.17 on 2026-09-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scenecapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenecapture',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
