# Generated by Django 5.2.17 on 2026-09-19 23:52

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def migrate_preset_keys(apps, schema_editor):
    # Historical presets encoded room identity after a colon.
    Layout = apps.get_model('api', 'SceneLayout')
    for row in Layout.objects.using(schema_editor.connection.alias).filter(session_key__contains=':').iterator():
        session, room = row.session_key.split(':', 1)
        if session and room:
            row.session_key, row.room_id = session, room
            row.save(update_fields=['session_key', 'room_id'], using=schema_editor.connection.alias)


def restore_preset_keys(apps, schema_editor):
    """Restore unique legacy keys before room_id is removed on rollback."""
    Layout = apps.get_model('api', 'SceneLayout')
    rows = list(Layout.objects.using(schema_editor.connection.alias).all())
    keys = set()
    updates = []
    for row in rows:
        key = row.session_key if row.room_id == 'demo-room' else f'{row.session_key}:{row.room_id}'
        # Prepared room IDs can be longer than the old schema supports. Never
        # silently truncate or destroy those layouts to make rollback succeed.
        if len(key) > 40 or key in keys:
            raise IrreversibleError('Room layouts cannot fit the legacy unique 40-character session keys; export or migrate those layouts before rollback.')
        keys.add(key)
        updates.append((row, key))
    for row, key in updates:
        row.session_key = key
        row.save(update_fields=['session_key'], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scenecapture_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenecapture',
            name='representation',
            field=models.CharField(default='photographic', max_length=32),
        ),
        migrations.AddField(
            model_name='scenelayout',
            name='geometry_revision',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='scenelayout',
            name='room_id',
            field=models.CharField(default='demo-room', max_length=128),
        ),
        migrations.AlterField(
            model_name='scenelayout',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.RunPython(migrate_preset_keys, restore_preset_keys),
        migrations.AddConstraint(
            model_name='scenelayout',
            constraint=models.UniqueConstraint(fields=('session_key', 'room_id'), name='unique_session_room'),
        ),
    ]
