# Generated by Django 5.2.17 on 2026-09-20 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_prepared_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneDesignJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("phase", models.CharField(default="before", max_length=32)),
                ("data", models.JSONField(default=dict)),
                ("result", models.JSONField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.scenelayout",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "request_id"),
                        name="unique_scene_design_request",
                    )
                ],
            },
        ),
    ]
