# Generated by Django 5.2.17 on 2026-09-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="cart_revision",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shopping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shopping.shoppingsession",
            ),
        ),
    ]
