# Generated by Django 5.2.17 on 2026-09-19 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SandboxAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("trans_id", models.UUIDField(unique=True)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("state", models.CharField(default="validated", max_length=32)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
